resources:
- repo: self
  clean: true

trigger:
  branches:
    include:
    - master
    - develop
  paths:
    include:
    - databricks-cluster-config.json

stages:
- stage: release
  condition: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
  - job: deploy_databricks
    displayName: 'Deploy Databricks'
    timeoutInMinutes: 30
    pool:
      vmImage: 'windows-latest'
    steps:

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # Connect to Azure using managed Identity
          Connect-AzAccount
          Import-Module -Name azure.databricks.cicd.tools
      displayName: 'Azure Connect'

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Install-Module -Name azure.databricks.cicd.tools -Scope CurrentUser
          Import-Module -Name azure.databricks.cicd.tools
      displayName: 'Install databricks cicd tools'

    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: $(System.DefaultWorkingDirectory)\generate_databricks_token.ps1
      displayName: 'Generate Databricks Token'

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: Connect-Databricks -BearerToken "dapi1234567890" -Region "westeurope"
      displayName: 'Databricks connect'

    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: $(System.DefaultWorkingDirectory)\create_databricks_cluster.ps1
      displayName: 'Create databricks cluster'

    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: $(System.DefaultWorkingDirectory)\check_cluster_creation.ps1
      displayName: 'Check if cluster created'
